@startuml
'https://plantuml.com/use-case-diagram



rectangle Database
User as User
rectangle "Population Information System" {

User --> (Use the application)
(Use the application) ..> (Generate report) : include
(Generate report) - Database
(Generate report) --> (View Countries by population)
(Generate report) --> (View Top N Populated Countries)
(Generate report) --> (View Cities by population)
(Generate report) --> (View Top N Populated Cities)
(Generate report) --> (View Capital Cities by population)
(Generate report) --> (View Top N Populated Capital Cities)
(Generate report) --> (View Population Report)
(Generate report) --> (Provide number of people who speak a certain language)

}



@enduml